spring.application.name=producer-service
server.port=8080

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/taskscheduler
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME:}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:}

# JWT secret
jwt.secret=${JWT_SECRET}
