spring.application.name=producer-service


# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/taskscheduler
spring.datasource.username=postgres
spring.datasource.password=rahul@756
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
