spring.application.name=worker-service


server.port=8081

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/taskscheduler
spring.datasource.username=postgres
spring.datasource.password=rahul@756
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379